# Generated by Django 5.0.4 on 2025-04-28 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
                ('rut', models.CharField(max_length=12)),
                ('nombre_completo', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('sexo', models.CharField(max_length=10)),
                ('telefono', models.CharField(max_length=15)),
                ('fecha_nacimiento', models.DateField()),
                ('metodo_pago', models.CharField(max_length=50)),
                ('fecha_contratacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
