# Generated by Django 5.0.4 on 2025-04-29 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('dia', models.CharField(max_length=20)),
                ('hora', models.TimeField()),
                ('profesor', models.CharField(blank=True, max_length=100)),
                ('duracion_minutos', models.IntegerField(default=60)),
            ],
        ),
    ]
